# config/packages/security.yaml
security:
    enable_authenticator_manager: true
# https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        login:
            pattern: ^/user/login
            stateless: true
            # json_login:
            #     check_path: /user/login
            #     success_handler: lexik_jwt_authentication.handler.authentication_success
            #     failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern: ^/user/register
            stateless: false
        api:
            pattern:   ^/user
            stateless: true
            jwt: ~

    access_control:
         # Permitir acceso anónimo a la ruta de registro de usuarios
        - { path: ^/user/register$, roles: PUBLIC_ACCESS }

        # Permitir acceso anónimo a la ruta de login de usuarios
        - { path: ^/user/login$, roles: PUBLIC_ACCESS }

        # Restringir todas las demás rutas bajo /user a usuarios autenticados
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }